### ISSUE TITLE
No commit in repository after getting successful commit on Igniton

### ISSUE THREAD

**Issue by battoyyeb** [AXONE-IO/ignition-git-module#19]
@AXONE-IO 
I successfully integrate my gitlab with Ignition (tried both ssh keys and user password) and I always get successful commit on Ignition designer but nothing is committed into my repository. I found out that when I open the project on designer, no .git folder was created in my project files.

**Comment by AXONE-IO** [comment]
@battoyyeb,

If the .git has not been created, this means that the connection has not been established with the repo.
Please note that .git is a hidden folder by default.

Are you starting from a blank Github project? 
Does the Git user used in Ignition have rights to use the repo ?

Once the first connection has been established, you'll see an "Initial Commit" on your git repo.
This means your project is ready to use.
Don't forget to push after committing, to send the changes to the remote server.

For start from a non-blank repo in which an Ignition project already exists, you need to use the [Commissioning File](https://www.axone-io.com/Files/Modules/GIT/1.0.2/doc/index.html#Commissioning-configuration-file).

**Comment by battoyyeb** [comment]
@AXONE-IO 
I found the hidden file and true the .git file was there. But I still have a problem, I did not see my ignition project on GitLab after I commit and push.

The reason for this is the branch name. My GitLab is using main but I think yours was hardcoded to use master. 

How can I change this?

**Comment by MowFord** [comment]
@battoyyeb to clarify: when you commit, it stores a change in the local git repository. The only time it pushes to the remote is when you click the "push" arrow in the git toolbar in designer.

Sidenote: this allows you to have git credentials for the repo repo only on a few users but many ignition designer users can still save/commit changes
