### ISSUE TITLE
Create releases

### ISSUE THREAD

**Issue by jasperlg** [AXONE-IO/ignition-git-module#4]
It would be useful for users to see all the releases of the past and to have a build version ready to download. This is supported in GIT. 
See [ignition-apexcharts-module](https://github.com/Kyvis-Labs/ignition-apexcharts-module) for inspiration.

**Comment by AXONE-IO** [comment]
Very good idea, I'll do it!

**Comment by AXONE-IO** [comment]
@jasperlg 
It's done ! Let me know if it looks good for you !
