### ISSUE TITLE
Exported Tags Missing New Line Characters

### ISSUE THREAD

**Issue by spsingletary** [AXONE-IO/ignition-git-module#6]
After upgrading to v1.0.1, the exported tags no longer have new line carriage returns. This makes it difficult to peer review others tag changes as part of a pull request.

Previously:
![image](https://user-images.githubusercontent.com/15251561/235733569-5e4d4c58-339e-42ae-9420-a9389ee12c20.png)

Currently:
![image](https://user-images.githubusercontent.com/15251561/235733444-50c749bf-acd5-4a6c-90b9-6836ff19f14e.png)

**Comment by AXONE-IO** [comment]
Thanks for your feedback!
I just fixed the bug in [this commit](https://github.com/AXONE-IO/ignition-git-module/commit/97e3856abe40de2db55c47fcb734a204b9127839).

The fix will be available in the next release.

**Comment by AXONE-IO** [comment]
Here is the release associated with this issue : [Release 1.0.2](https://github.com/AXONE-IO/ignition-git-module/releases/tag/1.0.2)
